### ISSUE TITLE
[mobileOSS] Please release complete kernel source

### ISSUE THREAD

**Issue by muhammadrafiasyddiq** [vivo/.github#1]
HEI VIVO SH*T PLEASE COMPLETE SOURCE KERNEL

WHY DOES VIVO DON'T LISTEN TO USER INPUT PLEASE RELEASE FULL KERNEL SOURCE @NODE PLEASE ALSO TELL VIVO TEAM-KERNEL WHY VIVO IS VERY STINGY FROM SOME BBK TEAM 

I would say Vivo is Very Stingy Please See My Feedback I Have Dizzy Kernel Vivo Has 80% Failure With Drivers Charger,PEM,RTC And other

**Comment by NeonzGamingYT** [comment]
gamau gasuka gelay

**Comment by NeonzGamingYT** [comment]
> HEI VIVO SH*T PLEASE COMPLETE SOURCE KERNEL
> 
> WHY DOES VIVO DON'T LISTEN TO USER INPUT PLEASE RELEASE FULL KERNEL SOURCE @node PLEASE ALSO TELL VIVO TEAM-KERNEL WHY VIVO IS VERY STINGY FROM SOME BBK TEAM
> 
> I would say Vivo is Very Stingy Please See My Feedback I Have Dizzy Kernel Vivo Has 80% Failure With Drivers Charger,PEM,RTC And other

Gamau gak suka gelay
